spring:
  datasource:
    password: PasswordTest123#
    url: jdbc:postgresql://192.168.1.177:5432/dnd_api
    username: dnd_api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dnd
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true