DROP SCHEMA DND CASCADE;
CREATE SCHEMA DND;

CREATE TABLE DND.USERS (
    USER_UID varchar NOT NULL,
    USER_NAME varchar(50) NOT NULL,
    USER_MAIL char(50) NOT NULL,
    CONSTRAINT "USERS_PK" PRIMARY KEY (USER_UID)
);

CREATE TABLE DND.CHARACTERS (
    CHARACTER_UID varchar NOT NULL,
    USER_UID varchar NOT NULL,
    CHARACTER_NAME varchar(50) NOT NULL,
    CHARACTER_STRENGTH int NOT NULL default 0,
    CHARACTER_DEXTERITY int NOT NULL default 0,
    CHARACTER_CONSTITUTION int NOT NULL default 0,
    CHARACTER_INTELLIGENCE int NOT NULL default 0,
    CHARACTER_WISDOM int NOT NULL default 0,
    CHARACTER_CHARISMA int NOT NULL default 0,
    CONSTRAINT "CHARACTERS_PK" PRIMARY KEY (CHARACTER_UID),
    CONSTRAINT "CHARACTERS_USERS_FK" FOREIGN KEY (USER_UID) REFERENCES DND.USERS (USER_UID)
);

CREATE TABLE DND.CLASSES (
    CLASS_UID varchar NOT NULL,
    CLASS_NAME varchar(50) NOT NULL
);

CREATE TABLE DND.CHARACTER_CLASSES (
    CHARACTER_UID varchar NOT NULL,
    CLASS_UID varchar NOT NULL
);

